name: Build plugin demo
on: [push]
jobs:
  Build_PluginLockTCP:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
          
      - name: Install Qt with options
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          tools: qt.tools.qtcreator'

      - name: Configure test project on windows
        run: |
          cd PluginLockTCP
          echo "MS batch script"
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo "List in CMAKE"
          echo %Qt5_DIR%
          dir %Qt5_DIR%/lib/cmake
          echo "QMAKE"
          qmake
          nmake
          echo "Print outputs"
          dir C:\RoboDK\bin\plugins
          dir C:\RoboDK\bind\plugins
          dir
        shell: cmd
