name: Build plugin demo
on: [push]
jobs:
  Build TCP plugin:
    runs-on: windows-2019
    steps:
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.6'
          host: 'windows'
          target: 'desktop'

      - name: Configure test project on windows
        run: |
          cd PluginLockTCP
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          dir %Qt5_DIR%/lib/cmake
          qmake
        shell: cmd