name: Build plugin demo
on: [push]
jobs:
  Build_PluginLockTCP:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
          
      - name: Install Qt with options
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          tools: qt.tools.qtcreator'

      - name: Configure test project on windows
        run: |
          cd PluginLockTCP
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release
          nmake
        shell: cmd
        
      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            C:\RoboDK\bin\plugins
			
