name: Build plugins

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['5.15.2']
    steps:
      - uses: actions/checkout@v2
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.version }}

      - name: Configure and build PluginLockTCP on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd ${{ github.workspace }}\PluginLockTCP
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release
          nmake
        shell: cmd
        
      - name: Configure and build PluginLockTCP on Unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          cd ${{ github.workspace }}\PluginLockTCP
          qmake CONFIG+=release
          nmake
        shell: bash
        
      - name: Configure and build PluginAppLoader on Windows
        run: |
          cd ${{ github.workspace }}\PluginAppLoader
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release
          nmake
        shell: cmd
        
      - name: Configure and build PluginAppLoader on Unix
        run: |
          cd ${{ github.workspace }}\PluginAppLoader
          qmake CONFIG+=release
          nmake
        shell: bash
        
      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            C:\RoboDK\bin\plugins
