name: Build plugins

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['5.15.2']
    steps:
      - uses: actions/checkout@v2
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.version }}

      - name: Configure and build PluginLockTCP on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd ${{ github.workspace }}\PluginLockTCP
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release
          nmake
        shell: cmd
        
      - name: Configure and build PluginLockTCP on Unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          cd ${{ github.workspace }}/PluginLockTCP
          qmake CONFIG+=release
          cmake ${{ github.workspace }}/PluginLockTCP
        shell: bash
        
      - name: Configure and build PluginAppLoader on Windows
        if: startsWith(matrix.os, 'windows')
        run: |
          cd ${{ github.workspace }}/PluginAppLoader
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          qmake CONFIG+=release
          nmake
        shell: cmd
        
      - name: Configure and build PluginAppLoader on Unix
        if: (!startsWith(matrix.os, 'windows'))
        run: |
          cd ${{ github.workspace }}/PluginAppLoader
          qmake CONFIG+=release
          cmake ${{ github.workspace }}/PluginAppLoader
        shell: bash
        
      - name: Upload artefacts on Windows
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'windows')
        with:
          name: Plugins-Windows-x64
          path: |
            C:/RoboDK/bin/plugins
            
      - name: Upload artefacts on Linux
        uses: actions/upload-artifact@v2
        if: (startsWith(matrix.os, 'unbuntu'))
        with:
          name: Plugins-linux-x64
          path: |
            ~/RoboDK/bin/plugins

      - name: Upload artefacts on macOS
        uses: actions/upload-artifact@v2
        if: (startsWith(matrix.os, 'macos'))
        with:
          name: Plugins-macos-x64
          path: |
            ~/RoboDK-Dev/Deploy/RoboDK.app/Contents/MacOS/plugins
