name: Build plugins

on: [push]

env:
  BUILD_TYPE: release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            OUTPUT_DIR: C:/RoboDK/bin/plugins
            QT_VERSION: '5.15.2'
            SHELL: cmd
            MAKE: nmake
            ADD_PARAMS: call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          - os: ubuntu-latest
            OUTPUT_DIR: ~/RoboDK/bin/plugins
            QT_VERSION: '5.15.2'
            SHELL: bash
            MAKE: make
            ADD_PARAMS: ""

          - os: macos-latest
            OUTPUT_DIR: ~/RoboDK-Dev/Deploy/RoboDK.app/Contents/MacOS/plugins
            QT_VERSION: '5.15.2'
            SHELL: bash
            MAKE: make
            ADD_PARAMS: ""

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.QT_VERSION }}

      - name: Configure and build PluginLockTCP
        run: |
          cd ${{ github.workspace }}/PluginLockTCP
          ${{ matrix.ADD_PARAMS }}
          qmake CONFIG+=${{ env.BUILD_TYPE }}
          ${{ matrix.MAKE }}
        shell: ${{ matrix.SHELL }}

      - name: Configure and build PluginAppLoader
        run: |
          cd ${{ github.workspace }}/PluginAppLoader
          ${{matrix.ADD_PARAMS}}
          qmake CONFIG+=${{ env.BUILD_TYPE }}
          ${{ env.MAKE }}
        shell: ${{ env.SHELL }}

      - name: Upload artefacts
        uses: actions/upload-artifact@v2
        with:
          name: Plug-In-Interface-${{ matrix.os }}-${{ env.BUILD_TYPE }}
          path: ${{ matrix.OUTPUT_DIR }}
